### PR TITLE
lua: remove ufs usage (#78) and fix premake file

### LINKED ISSUE #78: missing lua ufs module for building this tutorial
Originally reported by: **Ilya Ermolin (Bitbucket: [cgi](http://bitbucket.org/cgi), GitHub: [cgi](http://github.com/cgi))**

---

Hi, I try to make this tutorial local from and get problem to get ufs module around internet. Googling give ferrerenses for this repository only...

Where I can get this lib?

---
- Bitbucket: https://bitbucket.org/alfonse/gltut/issue/109

### PR DESCRIPTION
**Pull request by LeonardKoenig**
This removes the usage of `ufs` and `ex` `get_externals.lua` (fixes #78). Changes:
 - remove `_FindFileInPath.lua` because it's not really needed. If one'd care about this, one can always check the return value of `os.execute()`
 - require LuaFileSystem `lfs`
 - update the link to the glSDK (and update it from 0.4.2 to 0.5.2)
 - use `7z` instead of `7z.exe` as binary name, I've no Windows to test on anyway
 - implement a `RecursiveDelete()` function as replacement to `ufs.remove_all()`
 - rewrite `RecursiveCopy()` to only use LFS and IO
 - use UNIX style paths
 - use `os.execute()` instead of `ex.spawn()` since the latter segfaulted and can be considered deprecated (lua51 only)
 - also fixing the premake `SetupFrameworkProj()` function
 
This also makes the script compatible to lua5.3

### CODE REVIEW

File: get_externals.lua [hunk 1]
```diff
@@ -35,85 +33,100 @@ local externals =
 	},
 }
 
-local zipFullName = FindFileInPath("7z.exe");
+local zipFullName = "7z"
```
Comment (paroj) [inline get_externals.lua]: as this will probably only work on linux, you can also use `7zr` here which is installed by default on ubuntu while `7z` is not

Comment (LeonardKoenig) [inline get_externals.lua]: Yep, I'm on ArchLinux and here both are just shell-scritps containing:

```bash
#! /bin/sh
"/usr/lib/p7zip/7z" "$@"
```
